background=0841
panel=1084
row=18c6
edge=39c7
accent=fda0
accent2=56b5
dark=0020
text_title=ffff
text_primary=ffff
text_selected=0841
text_muted=ad55
text_selected_muted=2945
text_footer=bdf7
text_warning=ff60
home_layout=systems
icon_root=/media/mmcblk0/unifrog/themes/system-icons
icon_gba=icons/gba.png
icon_gb=icons/gb.png
icon_nes=icons/nes.png
icon_snes=icons/snes.png
icon_genesis=icons/genesis.png
icon_pcengine=icons/pcengine.png
icon_psx=icons/psx.png
icon_media=icons/media.png
icon_firmware=icons/firmware.png
icon_last=icons/continue.png
icon_settings=icons/settings.png
icon_files=icons/files.png
icon_index=icons/index.png
icon_developer=icons/developer.png
# font=/media/mmcblk0/unifrog/font.ufnt
