#ifndef UNIFROG_FASTBOOT_HANDOFF_H
#define UNIFROG_FASTBOOT_HANDOFF_H

#define FASTBOOT_CHUNK_ADDR 0x87fe7000u
#define FASTBOOT_STAGE1_ADDR 0x87ff7000u
#define FASTBOOT_STACK_ADDR 0x87fff000u
#define FASTBOOT_EXCEPTION_BASE 0x87fff700u
#define FASTBOOT_TRACE_BASE 0x87fff780u
#define FASTBOOT_ACTIVITY_BASE 0x87fffdc0u
#define FASTBOOT_DIAG_BASE 0x87fffe00u
#define FASTBOOT_REGS_BASE 0x87fffe70u
#define FASTBOOT_HANDOFF_BASE 0x87ffff00u
#define FASTBOOT_HANDOFF_MAGIC 0x55464248u
#define FASTBOOT_DIAG_MAGIC 0x55464244u
#define FASTBOOT_EXCEPTION_MAGIC 0x55464245u
#define FASTBOOT_EXCEPTION_VERSION 3u
#define FASTBOOT_EXCEPTION_EPC_WORDS 4u
#define FASTBOOT_EXCEPTION_STACK_WORDS 8u
#define FASTBOOT_ACTIVITY_MAGIC 0x55464241u
#define FASTBOOT_ACTIVITY_VERSION 1u
#define FASTBOOT_ACTIVITY_FLAG_ARMED 1u
#define FASTBOOT_REGS_MAGIC 0x55464252u
#define FASTBOOT_REGS_VERSION 1u
#define FASTBOOT_REGS_WORDS 32u
#define FASTBOOT_TRACE_MAGIC 0x55464254u
#define FASTBOOT_TRACE_VERSION 1u
#define FASTBOOT_TRACE_ENTRIES 64u
#define FASTBOOT_HANDOFF_PATH_BYTES 96u
#define FASTBOOT_PINMUX_R05_ADDR 0xb88004e5
#define FASTBOOT_GPIOR_OUTPUT_REG 0xb88000f4
#define FASTBOOT_GPIOR_DIR_REG 0xb88000f8
#define FASTBOOT_BACKLIGHT_R05_MASK 0x20

#define FASTBOOT_TRACE_MAGIC_OFFSET 0u
#define FASTBOOT_TRACE_VERSION_OFFSET 4u
#define FASTBOOT_TRACE_COUNT_OFFSET 8u
#define FASTBOOT_TRACE_DROPPED_OFFSET 12u
#define FASTBOOT_TRACE_ENTRY_OFFSET 16u
#define FASTBOOT_TRACE_ENTRY_SIZE 24u
#define FASTBOOT_TRACE_ENTRY_SEQ_OFFSET 0u
#define FASTBOOT_TRACE_ENTRY_EVENT_OFFSET 4u
#define FASTBOOT_TRACE_ENTRY_ARG0_OFFSET 8u
#define FASTBOOT_TRACE_ENTRY_ARG1_OFFSET 12u
#define FASTBOOT_TRACE_ENTRY_ARG2_OFFSET 16u
#define FASTBOOT_TRACE_ENTRY_R05_OFFSET 20u

#define FASTBOOT_TRACE_STUB_BACKLIGHT_OFF 1u
#define FASTBOOT_TRACE_STAGE1_START 10u
#define FASTBOOT_TRACE_STAGE1_BACKLIGHT_OFF 11u
#define FASTBOOT_TRACE_STAGE1_MOUNT_RESULT 12u
#define FASTBOOT_TRACE_STAGE1_HANDOFF_RESULT 13u
#define FASTBOOT_TRACE_STAGE1_LOAD_START 14u
#define FASTBOOT_TRACE_STAGE1_LOAD_DONE 15u
#define FASTBOOT_TRACE_STAGE1_ASD_START 16u
#define FASTBOOT_TRACE_STAGE1_ASD_DONE 17u
#define FASTBOOT_TRACE_STAGE1_JUMP 18u
#define FASTBOOT_TRACE_STAGE1_FAIL 19u
#define FASTBOOT_TRACE_STAGE1_INPUT_OVERRIDE 20u
#define FASTBOOT_TRACE_STAGE1_DEFAULT_RESULT 21u

#define FASTBOOT_TRACE_UNIFROG_MAIN_START 100u
#define FASTBOOT_TRACE_UNIFROG_APP_MAIN_START 101u
#define FASTBOOT_TRACE_UNIFROG_MODULE_INIT_BEGIN 102u
#define FASTBOOT_TRACE_UNIFROG_MODULE_INIT_DONE 103u
#define FASTBOOT_TRACE_UNIFROG_FRONTEND_THREAD_START 104u
#define FASTBOOT_TRACE_UNIFROG_BOARD_INIT_BEGIN 105u
#define FASTBOOT_TRACE_UNIFROG_BOARD_INIT_DONE 106u
#define FASTBOOT_TRACE_UNIFROG_STORAGE_DONE 107u
#define FASTBOOT_TRACE_UNIFROG_LOG_RESET_DONE 108u
#define FASTBOOT_TRACE_UNIFROG_FRONTEND_BEGIN 109u
#define FASTBOOT_TRACE_UNIFROG_FB_OPEN_BEGIN 110u
#define FASTBOOT_TRACE_UNIFROG_FB_CLEAR_DONE 111u
#define FASTBOOT_TRACE_UNIFROG_BOOT_LOGO_DONE 112u

#define FASTBOOT_TRACE_SDK_PWM_PROBE_BEGIN 200u
#define FASTBOOT_TRACE_SDK_PWM_PINMUX_ACTIVE 201u
#define FASTBOOT_TRACE_SDK_PWM_REGISTER_DONE 202u
#define FASTBOOT_TRACE_SDK_BACKLIGHT_PROBE_BEGIN 210u
#define FASTBOOT_TRACE_SDK_BACKLIGHT_DEFAULT_OFF 211u
#define FASTBOOT_TRACE_SDK_BACKLIGHT_PWM_DUTY 212u
#define FASTBOOT_TRACE_SDK_BACKLIGHT_GPIO_STATUS 213u
#define FASTBOOT_TRACE_SDK_BACKLIGHT_WRITE 214u
#define FASTBOOT_TRACE_SDK_LCD_PROBE_BEGIN 220u
#define FASTBOOT_TRACE_SDK_LCD_DISPLAY_BEGIN 221u
#define FASTBOOT_TRACE_SDK_LCD_RESET_DONE 222u
#define FASTBOOT_TRACE_SDK_LCD_PANEL_PROBE_DONE 223u
#define FASTBOOT_TRACE_SDK_LCD_INIT_SEQ_DONE 224u
#define FASTBOOT_TRACE_SDK_LCD_DISPON 225u
#define FASTBOOT_TRACE_SDK_LCD_RGB_ON 226u
#define FASTBOOT_TRACE_SDK_FB_PROBE_BEGIN 240u
#define FASTBOOT_TRACE_SDK_FB_ALLOC_DONE 241u
#define FASTBOOT_TRACE_SDK_FB_REGISTER_DONE 242u
#define FASTBOOT_TRACE_SDK_FB_GMA_OFF 243u

#ifndef __ASSEMBLER__

#include <stdint.h>

#define FASTBOOT_TRACE_ADDR ((volatile struct fastboot_trace *)FASTBOOT_TRACE_BASE)
#define FASTBOOT_DIAG_ADDR ((volatile struct fastboot_diag *)FASTBOOT_DIAG_BASE)
#define FASTBOOT_HANDOFF_ADDR ((volatile struct fastboot_handoff *)FASTBOOT_HANDOFF_BASE)
#define FASTBOOT_EXCEPTION_ADDR ((volatile struct fastboot_exception_record *)FASTBOOT_EXCEPTION_BASE)
#define FASTBOOT_ACTIVITY_ADDR ((volatile struct fastboot_activity_record *)FASTBOOT_ACTIVITY_BASE)
#define FASTBOOT_REGS_ADDR ((volatile struct fastboot_exception_regs *)FASTBOOT_REGS_BASE)

struct fastboot_handoff {
   uint32_t magic;
   char path[FASTBOOT_HANDOFF_PATH_BYTES];
};

struct fastboot_diag {
   uint32_t magic;
   uint32_t stage_addr;
   uint32_t event;
   int32_t result;
   char path[FASTBOOT_HANDOFF_PATH_BYTES];
};

struct fastboot_trace_entry {
   uint32_t seq;
   uint32_t event;
   uint32_t arg0;
   uint32_t arg1;
   uint32_t arg2;
   uint32_t r05_state;
};

struct fastboot_trace {
   uint32_t magic;
   uint32_t version;
   uint32_t count;
   uint32_t dropped;
   struct fastboot_trace_entry entries[FASTBOOT_TRACE_ENTRIES];
};

struct fastboot_exception_record {
   uint32_t magic;
   uint32_t version;
   uint32_t cause;
   uint32_t epc;
   uint32_t badvaddr;
   uint32_t ra;
   uint32_t count;
   uint32_t status;
   uint32_t sp;
   uint32_t task;
   uint32_t irq_nesting;
   uint32_t phase;
   uint32_t marker;
   uint32_t heartbeat;
   uint32_t detail0;
   uint32_t detail1;
   uint32_t epc_section;
   uint32_t ra_section;
   uint32_t gp;
   uint32_t epc_words[FASTBOOT_EXCEPTION_EPC_WORDS];
   uint32_t stack_words[FASTBOOT_EXCEPTION_STACK_WORDS];
   uint32_t checksum;
};

struct fastboot_activity_record {
   uint32_t magic;
   uint32_t version;
   uint32_t flags;
   uint32_t phase;
   uint32_t marker;
   uint32_t heartbeat;
   uint32_t detail0;
   uint32_t detail1;
   uint32_t count;
   uint32_t checksum;
};

struct fastboot_exception_regs {
   uint32_t magic;
   uint32_t version;
   uint32_t count;
   uint32_t checksum;
   uint32_t regs[FASTBOOT_REGS_WORDS];
};

#endif

#endif
