#ifndef UNIFROG_PATHS_H
#define UNIFROG_PATHS_H

#define UNIFROG_SD_ROOT "/media/mmcblk0"
#define UNIFROG_ROMS_ROOT UNIFROG_SD_ROOT "/ROMS"
#define UNIFROG_DIST_ROOT UNIFROG_SD_ROOT "/unifrog"
#define UNIFROG_DATA_ROOT UNIFROG_SD_ROOT "/unifrog_data"
#define UNIFROG_BIOS_ROOT UNIFROG_SD_ROOT "/bios"

#define UNIFROG_DIST_FIRMWARE_ROOT UNIFROG_DIST_ROOT "/firmware"
#define UNIFROG_DIST_FIRMWARE_PATH \
   UNIFROG_DIST_FIRMWARE_ROOT "/unifrog.bin"
#define UNIFROG_DIST_MANIFEST_PATH UNIFROG_DIST_ROOT "/manifest.ini"
#define UNIFROG_CORE_ROOT UNIFROG_DIST_ROOT "/cores"
#define UNIFROG_MODULE_ROOT UNIFROG_DIST_ROOT "/modules"

#define UNIFROG_SAVE_ROOT UNIFROG_DATA_ROOT "/saves"
#define UNIFROG_CACHE_ROOT UNIFROG_DATA_ROOT "/cache"
#define UNIFROG_LOG_ROOT UNIFROG_DATA_ROOT "/logs"
#define UNIFROG_REPORT_ROOT UNIFROG_LOG_ROOT "/reports"
#define UNIFROG_SCREENSHOT_ROOT UNIFROG_DATA_ROOT "/screenshots"
#define UNIFROG_SCRIPT_ROOT UNIFROG_DATA_ROOT "/scripts"
#define UNIFROG_THEME_ROOT UNIFROG_DATA_ROOT "/themes"
#define UNIFROG_LANGUAGE_ROOT UNIFROG_DATA_ROOT "/languages"
#define UNIFROG_ARCHIVE_ROOT UNIFROG_DATA_ROOT "/archive"
#define UNIFROG_UPDATE_ROOT UNIFROG_DATA_ROOT "/updates"
#define UNIFROG_VERSION_ROOT UNIFROG_DATA_ROOT "/versions"
#define UNIFROG_USER_FIRMWARE_ROOT UNIFROG_DATA_ROOT "/firmware"

#define UNIFROG_SETTINGS_PATH UNIFROG_DATA_ROOT "/settings.ini"
#define UNIFROG_HISTORY_PATH UNIFROG_DATA_ROOT "/history.txt"
#define UNIFROG_FAVORITES_PATH UNIFROG_DATA_ROOT "/favorites.txt"
#define UNIFROG_ACTIVE_VERSION_PATH UNIFROG_DATA_ROOT "/active-version.ini"
#define UNIFROG_PENDING_VERSION_PATH UNIFROG_DATA_ROOT "/pending-activation.ini"
#define UNIFROG_BOOT_OK_PATH UNIFROG_DATA_ROOT "/boot-ok.ini"
#define UNIFROG_PACKAGE_CHECK_PATH UNIFROG_DATA_ROOT "/package-check.txt"
#define UNIFROG_CRASH_MARKER_PATH UNIFROG_DATA_ROOT "/last-crash.ini"
#define UNIFROG_FRONTEND_DRIVER_STATE_PATH \
   UNIFROG_DATA_ROOT "/frontend-driver.state"
#define UNIFROG_FRONTEND_DRIVER_REPORT_PATH \
   UNIFROG_REPORT_ROOT "/frontend-driver-report.txt"

#endif
