#ifndef UNIFROG_EXCEPTION_RECORD_H
#define UNIFROG_EXCEPTION_RECORD_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum unifrog_exception_activity_phase {
   UNIFROG_ACTIVITY_PHASE_NONE = 0,
   UNIFROG_ACTIVITY_PHASE_BOOT = 1,
   UNIFROG_ACTIVITY_PHASE_DMA = 2,
   UNIFROG_ACTIVITY_PHASE_FRONTEND_START = 3,
   UNIFROG_ACTIVITY_PHASE_FRONTEND_STORAGE = 4,
   UNIFROG_ACTIVITY_PHASE_EXTERNAL_CORE_BEGIN = 10,
   UNIFROG_ACTIVITY_PHASE_EXTERNAL_CORE_LOAD = 11,
   UNIFROG_ACTIVITY_PHASE_EXTERNAL_CORE_API = 12,
   UNIFROG_ACTIVITY_PHASE_LIBRETRO_BEGIN = 20,
   UNIFROG_ACTIVITY_PHASE_LIBRETRO_API = 21,
   UNIFROG_ACTIVITY_PHASE_LIBRETRO_CALLBACKS = 22,
   UNIFROG_ACTIVITY_PHASE_CONTENT_PREPARE = 30,
   UNIFROG_ACTIVITY_PHASE_CORE_INIT = 40,
   UNIFROG_ACTIVITY_PHASE_RETRO_LOAD_GAME = 50,
   UNIFROG_ACTIVITY_PHASE_SAVE_LOAD = 60,
   UNIFROG_ACTIVITY_PHASE_PRESENTER_OPEN = 70,
   UNIFROG_ACTIVITY_PHASE_AUDIO_OPEN = 71,
   UNIFROG_ACTIVITY_PHASE_RUN_FRAME = 80,
   UNIFROG_ACTIVITY_PHASE_SAVE_MEMORY = 90,
   UNIFROG_ACTIVITY_PHASE_UNLOAD_GAME = 91,
   UNIFROG_ACTIVITY_PHASE_DEINIT = 92,
   UNIFROG_ACTIVITY_PHASE_FINISH = 100,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_BEGIN = 120,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_OPEN = 121,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_HEADER = 122,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_VALIDATE = 123,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_READ = 124,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_BSS = 125,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_CACHE = 126,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_ENTRY = 127,
   UNIFROG_ACTIVITY_PHASE_CORE_MODULE_DONE = 128,
   UNIFROG_ACTIVITY_PHASE_MEDIA = 130,
   UNIFROG_ACTIVITY_PHASE_MEDIA_AUDIO = 131,
   UNIFROG_ACTIVITY_PHASE_MEDIA_VIDEO = 132,
   UNIFROG_ACTIVITY_PHASE_LOG_FLUSH = 140,
   UNIFROG_ACTIVITY_PHASE_LOG_RESET = 141,
   UNIFROG_ACTIVITY_PHASE_LOG_RECOVERY = 142,
   UNIFROG_ACTIVITY_PHASE_REPORT_WRITE = 150,
};

void unifrog_exception_record_store(uint32_t cause, uint32_t epc,
   uint32_t badvaddr, uint32_t ra);
int unifrog_exception_record_peek(uint32_t *cause, uint32_t *epc,
   uint32_t *badvaddr, uint32_t *ra, uint32_t *count);
void unifrog_exception_record_log_and_clear(const char *tag);
uint32_t unifrog_exception_activity_hash(const char *text);
void unifrog_exception_activity_set(uint32_t phase, uint32_t marker,
   uint32_t detail0, uint32_t detail1);
void unifrog_exception_activity_clear(void);
void unifrog_exception_activity_log_and_clear(const char *tag);

#ifdef __cplusplus
}
#endif

#endif
